version: '3.8'
services:
  web:
    build: .
    image: gihyosd_app_web
    container_name: gihyosd_app_web
    command: ["./wait-for-it.sh", "db:3306", "--", "./start.sh"]
    ports:
      - '3000:3000'
    volumes:
      - .:/gihyosd_app
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    container_name: gihyosd_app_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'gihyosd_app_development'
volumes:
  mysql_data:
    name: gihyosd_mysql_data